language: csharp
solution: MongoDbRepository.sln
services:
  - mongodb
before_script:
  - sleep 15
notifications:
  email:
    recipients:
      - serkanyazicioglu@gmail.com
    on_success: always
    on_failure: always