name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
     mongo:
      image: mongo
      ports: 
      - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore *.sln

    - name: Build
      run: dotnet build *.sln --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test */TestProject.csproj --configuration Release
